#pragma once

#include <AP_Common/AP_CPU_Diagnostics_config.h>
#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_SCHEDULER_ENABLED
#define AP_SCHEDULER_ENABLED 1
#endif

#ifndef AP_SCHEDULER_EXTENDED_TASKINFO_ENABLED
#define AP_SCHEDULER_EXTENDED_TASKINFO_ENABLED 1
#endif

#ifndef AP_SCHEDULER_CPU_DIAGNOSTICS_ENABLED
#define AP_SCHEDULER_CPU_DIAGNOSTICS_ENABLED AP_CPU_DIAGNOSTICS_ENABLED
#endif
